version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Ljubljana
    open-pull-requests-limit: 5
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Ljubljana
    open-pull-requests-limit: 3
